services:
  test-website:
    image: nginx:latest
    container_name: test-website
    volumes:
      - /home/jacob/web/the_online_grid:/usr/share/nginx/html
    ports:
      - 7777:80
    restart: always
