services:
  rps-website:
    image: nginx:latest
    container_name: rps-website
    volumes:
      - /home/jacob/web/the_online_grid:/usr/share/nginx/html
    ports:
      - 80:80
    restart: always
